### ISSUE TITLE
Plugin graphics

### ISSUE THREAD

**Issue by Justinfront** [hxDaedalus/hxDaedalus#32]
Snow has drawing code:
http://www.luxeengine.com/docs/guide.drawing.html

Graphics in hxDaedalus should be implemented more as a plugin type?

**Comment by azrafe7** [comment]
Oh, we've briefly discussed this exact subject in _some_ way (in #17 and #23)...

my proposal is to move all that in an external package, so that the core of hxDaedalus has no dependencies (apart from the uncomfortably obvious-but-unavoidable? Pixels).

Moving the graphics out of the core, **but** still providing a SimpleView and a SimpleDrawingContext which the end users has to implement, seems a great thing to have to me. They have an easy way to get an overview of what's happening, at the small cost of ~implementing an interface (5/6 methods).

**Comment by Justinfront** [comment]
should we leave separation till webgl ( luxe and flambe ) and lwjgl are working as they may force some better structures prior to separation or is it likely the other way round just conscious we are very flash focused in the graphics interface decisions but maybe that does not matter.

**Comment by Justinfront** [comment]
Been talking on the snow chat with underscoreddiscovery and it looks like we should really be looking at Geometry we can change the primative type to a range of options.

var shape = new phoenix.geometry.Geometry({
    primitive_type:PrimitiveType.triangles,
    batcher: Luxe.renderer.batcher
});
shape.add(new phoenix.geometry.Vertex( new Vector(0,0), new Color(1,0,0,1)));

but maybe we need quite a lot of changes to make this easy I expect inside flambe is similar?
