### ISSUE TITLE
Flambe support

### ISSUE THREAD

**Issue by azrafe7** [hxDaedalus/hxDaedalus#34]
I've started working on supporting flambe (see https://github.com/Justinfront/hxDaedalus/pull/33).

Managed to port the first two demos, but I'm having problems with the pathfinding one (03) and could not figure out what's wrong with mouse input. I'll try to get some help on IRC in the next days.

Flash seems quite slower related to html, not sure if it's my fault. Anyway I've uploaded 01 and 02 to dropbox to see if they worked:
[01-html](https://dl.dropboxusercontent.com/u/32864004/dev/FPDemo/hxDaedalus-examples/flambe/01-Basics/index.html?flambe=html) | [01-flash](https://dl.dropboxusercontent.com/u/32864004/dev/FPDemo/hxDaedalus-examples/flambe/01-Basics/index.html?flambe=flash) | [02-html](https://dl.dropboxusercontent.com/u/32864004/dev/FPDemo/hxDaedalus-examples/flambe/02-FromBitmap/index.html?flambe=html) | [02-flash](https://dl.dropboxusercontent.com/u/32864004/dev/FPDemo/hxDaedalus-examples/flambe/02-FromBitmap/index.html?flambe=flash)

When I'll get to make 03 work I'll make a proper PR to include them in the demos.

PS: where should they go? For now I have them in a "flambe" folder beside the openfl/nme examples.

**Comment by Justinfront** [comment]
I think really we should create a flambe one and later luxe one.  To cope with the mess of multiple example projects we can create a master demo github and then if they are sub git's normally git pulls the other ones in if setup correctly, and does not try to host the content might need to experiment to get this working well but I think it may prove a nice solution.

I can take a look at the mouse input are they in your fork?  I noticed on haxeui that the mouse target was not getting through on html5 target, you can cheat with callback in the mouse event setup if need be.  Also you can cast the type if the Event is wrong.  Maybe positions are offset, in java opengl haxe I found offsets due to the header often by about 20 or 30 pixels in y.  Webgl and opengl have some similarities so maybe there is something in how they work similar also Y seems reversed?
https://github.com/Justinfront/wwx2014_justinfront/blob/master/src/wwx2014_justinfront/bouncinglogo/BouncingLogo_lwjgl.hx#L30
Probably unrelated but it makes me think I should look into a lwjgl version so drawing the swing drawn graphics to lwjgl.  You will notice the IvanK that is flash ish js webgl with haxe externs but seems ideal as it has drawing code that might be good for blending into flambe but maybe really hard?

**Comment by azrafe7** [comment]
I've put the examples in the flambe branch [here](https://github.com/azrafe7/hxDaedalus-NME-OpenFL-Examples/tree/flambe). Being my first times working with flambe I'm probably misusing it/doing something wrong, hence the bug I was mentioning earlier (you can see my attempt at fixing it in the 3rd example, which so far has led me to a stack overflow in hittestbackwards()??).

I was thinking that instead of replicating the examples for all targets it might be better to make a new (more game-ish) one and port that. Meaning one using sprites and not needing SimpleView and drawing geometry.

**Comment by Justinfront** [comment]
I have created a logic only branch which only has pixel.hx in, and removed some debug features because they tied code to targets.  I have this running fine with an openfl multimap test that I was exploring for an application.
