### ISSUE TITLE
Luxe support

### ISSUE THREAD

**Issue by azrafe7** [hxDaedalus/hxDaedalus#38]
With help from the snowkit guys on gitter I've (seemingly) added Luxe support. It needed changes to Pixels & SimpleView-related classes. I've also ported two demos (01 and 04) while figuring out stuff. Still believe we should make a more practical demo, but porting those two aided me entering into the Luxe way of doing things.

The updated lib is [here](https://github.com/azrafe7/hxDaedalus/tree/luxe-support).

The examples are on this [luxe branch](https://github.com/azrafe7/hxDaedalus-NME-OpenFL-Examples/tree/luxe) (an online BitmapPathfinding demo I used as a test is [over here](https://dl.dropboxusercontent.com/u/32864004/dev/FPDemo/luxe-daedalus/bitmap-pathfinding/index.html)).

If you can confitm that all is working on your end I'll send a PR your way.

**Comment by azrafe7** [comment]
PS: there's still the issue of where to put the demos, can you take care of that?

**Comment by azrafe7** [comment]
PPS: ... aaand it should probably be safer to wait till haxe and openfl push out their next release, right?

**Comment by Justinfront** [comment]
azrafe7 I started to move repositories over to an organization since it helps organize them better can you move the luxe examples here and remove openfl aspects.
https://github.com/hxDaedalus/hxDaedalus-luxe-examples

**Comment by azrafe7** [comment]
Nice, thanks! ;D

I'll probably start pushing things in an hour or two (and maybe also add in the other examples provided I don't encounter obstacles).

**Comment by Justinfront** [comment]
only looked at your code so far not tried running it. Found this link https://help.github.com/articles/duplicating-a-repository/  So I can bare/mirror your code into this repository, but first will try do this to split the Examples one into Java, Javascript and Flash.

**Comment by azrafe7** [comment]
Ok, then I'll wait a bit.

**Comment by azrafe7** [comment]
Or not?!

Can I push only the relevant commits to the Luxe and Flambe repos (this was what I was going to do)?
Or do you want to mirror the nme/openfl repo and then delete unneeded stuff?

**Comment by Justinfront** [comment]
just a sec

**Comment by Justinfront** [comment]
Ok well I have mirrored openfl into new flambe and luxe branches but it does not seem to take the luxe branch with it, I tried reversing the arguments when getting the bare but when I tried mirror again it swares blind everything is upto date.  

So if you can pull your luxe code into the new luxe or maybe endup manually merging in the code then that would be great.  

I have hols at moment so I can tidy up at moment only mirror split the flash/swing/js and similar for the flambe/luxe/openfl.  Can you check if flambe still works fine removing openfl part from it. And try to update the new luxe one with your luxe code.

**Comment by Justinfront** [comment]
Not sure if it's a good idea to add luxe code to the hxDaedalus because I really wanted to separate the core maybe I can look at this more tomorrow.

I am off to salsa/kizomba/bachata but will be back later I have hols so I can put some time in tidying up stuff so don't worry if it's not all perfect hopefully I can remove extra code tomorrow and make the readme's better.  Just would be good to get your luxe code into the new one.

**Comment by Justinfront** [comment]
I can delete hxDaedalus-Examples when I have the other 3 repositories working and cleaned up.

**Comment by Justinfront** [comment]
so just stick with looking at new luxe and new flambe, leave openfl because it's broke anyway and I will look at other repositories tomorrow. Don't worry if you don't have time to create other luxe demo's no hurry especially with the multi one as I may want to improve that anyway.

**Comment by Justinfront** [comment]
probably be back from dancing around 1pm and may look through stuff more then, hope this seems a good plan. I saw the Luxe demo you linked running - really smooth :) very excited.

**Comment by azrafe7** [comment]
Ok, then I'll push the exampled to the new flambe and luxe repos.

But I also need to update the core to make it work with luxe (Pixels & SimpleDrawingContext)! Any problems with it?

I'd suggest to push the changes now (so we get the demos working) and later figure out how to bring them outside the core.

**Comment by Justinfront** [comment]
ok cool

**Comment by azrafe7** [comment]
Damn... I probably won't have time to do it tonight (though it's still to be seen). Anyway I should have no problems resuming work tomorrow. Sorry.

**Comment by Justinfront** [comment]
No worries :)

**Comment by azrafe7** [comment]
Sooo:

 - Demos for Flambe (01-03) and Luxe (01-05) have been added 
 - I've used gh-pages to link to the online demos of those two engines (so no more need to work around rawgit/github CORS issues) 
 - There's a PR waiting your approval for luxe support in the core 
 - Flambe seems to not support 3.2.0rc yet (I've tried with the git version but no luck either)
 - Some stale branches have been removed as they were no more needed

Let me know if all works for you, or I borked something along the way (... which is entirely possible hehe! ;D).

**Comment by Justinfront** [comment]
sounds good you made more progress I update the flash repo, removing unrelated code, I tidied up the code to my prefered style. Keeping the basic verbose whitespace but the other demos more compact. Seemed to take awhile I need to do same for swing and js.

**Comment by Justinfront** [comment]
I updated Java version and fixed a bug with mouseMoved by using mouseDragged as well. We need to add more examples to Java as well.

**Comment by Justinfront** [comment]
just been trying out your luxe stuff on my mac.  At moment getting an error on mac output.
ustins-MacBook-Pro:04-BitmapPathfinding justinfront$ haxelib run flow run mac
flow / 1.0.0-alpha.1
flow / target is mac ( arch 64 )
flow / haxe version 3.2.0

flow / project - searching project root /projects/hxDaedalus_/hxDaedalus-luxe-examples/hxDaedalus-Luxe-Examples/04-BitmapPathfinding
flow / project - using project file /projects/hxDaedalus_/hxDaedalus-luxe-examples/hxDaedalus-Luxe-Examples/04-BitmapPathfinding/project.flow
flow / build - BitmapPathfinding 1.0.0 for mac
flow / build - running haxe ...
flow / build - running hxcpp for arch 64 ...
g++ -o LuxeApp -stdlib=libstdc++ -framework Cocoa -m64 -l iconv -framework IOKit -framework Foundation -framework CoreAudio -framework CoreVideo -framework Cocoa -framework OpenGL -framework AudioToolbox -framework AudioUnit -framework ForceFeedback -framework Carbon -framework AppKit -framework OpenAL @obj/darwin64//all_objs /usr/lib/haxeLibrary/hxcpp/3,2,37/lib/Mac64/libregexp.a /usr/lib/haxeLibrary/hxcpp/3,2,37/lib/Mac64/libstd.a /usr/lib/haxeLibrary/hxcpp/3,2,37/lib/Mac64/libzlib.a /usr/lib/haxeLibrary/snow/git/ndll/Mac64/libsnow.a
clang: error: no such file or directory: '/usr/lib/haxeLibrary/snow/git/ndll/Mac64/libsnow.a'
Error: error running g++ -o LuxeApp -stdlib=libstdc++ -framework Cocoa -m64 -l iconv -framework IOKit -framework Foundation -framework CoreAudio -framework CoreVideo -framework Cocoa -framework OpenGL -framework AudioToolbox -framework AudioUnit -framework ForceFeedback -framework Carbon -framework AppKit -framework OpenAL @obj/darwin64//all_objs /usr/lib/haxeLibrary/hxcpp/3,2,37/lib/Mac64/libregexp.a /usr/lib/haxeLibrary/hxcpp/3,2,37/lib/Mac64/libstd.a /usr/lib/haxeLibrary/hxcpp/3,2,37/lib/Mac64/libzlib.a /usr/lib/haxeLibrary/snow/git/ndll/Mac64/libsnow.a
flow / 
 build - stopping because of errors in hxcpp compile, while building arch 64

**Comment by Justinfront** [comment]
But on web it all works very fast.  
The color depth of the galapagos islands looks very washed out, it looks much better in flash, any ideas why?  Also the render is a bit pixelated I am on a new mac so I don't know if we need to render at half size to get really smooth or if there are other tricks?

**Comment by Justinfront** [comment]
the flow versions are all 1.0.0  I believe these should really be changed to 0.0.3 to match the haxelib version that we next release?

**Comment by Justinfront** [comment]
Ah ok worked out getting it working native ( will doc here for anyone reading ). 
get the haxelibs needed and the ndll:

-cmd haxeLib git flow https://github.com/underscorediscovery/flow.git
-cmd haxeLib git snow https://github.com/underscorediscovery/snow.git
-cmd haxeLib git luxe https://github.com/underscorediscovery/luxe.git
-cmd curl -O http://build.luxeengine.com/snow/latest.mac.zip
-cmd curl -O http://build.luxeengine.com/snow/latest.android.zip

unzip put all the zipped files ( the -curl got ones ) they unzip to a ndll folder you will need to collate them into a single one and copy the ndll folder to the snow Haxelib folder in my case each of the targets goes here:

/usr/lib/haxeLibrary/snow/git/ndll

**Comment by azrafe7** [comment]
I've been without an internet connection in the last days, so wasn't able to respond. (anyway I think you can just download the `all` package from http://build.luxeengine.com/snow/, or build the libs from source from the `snow/git/` folder)

Don't know about the color depth thing, I've tried adding `texture.filter = FilterType.nearest` and changing the background color, but can't notice any difference.

Changing version to 0.0.3 into luxe/flambe project files makes sense (done!).

**Comment by userotti** [comment]
@Justinfront that sorted it for me. thanks.
