### ISSUE TITLE
extractFillTrianglesFromObjects

### ISSUE THREAD

**Issue by Justinfront** [hxDaedalus/hxDaedalus#46]
Azarafe7

I have added this method 
extractFillTrianglesFromObjects

It seems to work quite well with my experiment accept it misses the odd triangle, it may not be ideal implementation but it seems one way of getting fills by breaking down a drawn shape into triangles that can be filled.

I will try to link you a Luxe demo repo soon.

**Comment by Justinfront** [comment]
A screenshot of the result:
https://raw.githubusercontent.com/Justinfront/Letters/master/luxe.png
Updated Letters with this example.
https://github.com/Justinfront/Letters/blob/master/src/letters/luxe/TriangleFillExample.hx

**Comment by azrafe7** [comment]
Oh... that's interesting! I played with it trying to find a shorter way to get a triangulation of the letters. I've tried different approaches, but none seems to fit so far.

Maybe I'm doing it wrong, but it seems that iterating over `mesh._faces` doesn't give the result I'd expect (not sure if it's my fault, the original lib's, or our port's (or drawing stuff?)). Some of the edges are missing (see the 'x' f.e.), but I can't figure out why:

```haxe
    static public function extractTrianglesFromObjects( mesh: Mesh, vertices: Array<Point2D>, triangles: Array<Int> ): Void {
		var facesDone = new Map<Int, Bool>();
		var triIdx = triangles.length;
		var iter = new FromFaceToInnerVertices();
		
		for (currFace in mesh._faces) {
			if (/*facesDone[currFace.id] || */currFace.isReal) {
				iter.fromFace = currFace;
				var vertex:Vertex;
				
				while ((vertex = iter.next()) != null) {
					vertices.push(vertex.pos);
				}
				
				triangles.push(triIdx);
				triIdx += 3;
				
				facesDone[currFace.id] = true;
			}
		}
	}
```

![deadalus_triangulation_test](https://cloud.githubusercontent.com/assets/1266447/7827689/8760c204-042a-11e5-9c7b-4c4fcc5c37f7.png)

**Comment by azrafe7** [comment]
nvm, I was doing something stupid in my drawing code. :p

**Comment by Justinfront** [comment]
isReal does not seem to be very helpful.  We do need a simpler approach using pathfinding is most probably well overkill and the edge cases missed might be impossible to fix.  Maybe we should ask totallogic my implementation may give him some inspiration and help him find a solution faster.

**Comment by azrafe7** [comment]
Thinking about your use case, there's a chance it's not even possible to do it with hxDaedalus (or probably only doable for a subset of inputs). I am thinking of holes and non-closed (constrained) polylines... for example, what would be the expected output when passing a single constrained segment? Also, when condidering polygons with holes, since there's no winding information (or is it?) it's not easy to know if an edge is inside or outside. But still, Jules may know better.

For a shameless plug, anyway, if you don't mind not having a Delaunay triangulation, you can try using the Tess2 class in hxGeomAlgo, which supports holes.

**Comment by azrafe7** [comment]
Mmmhh... searching about this (Delaunay + holes), it might actually be possible by doing the triangulation and then remove the objects representing holes. So it's doable in theory. I'll experiment more with this idea. cc @totologic

**Comment by Justinfront** [comment]
I think that the pathfinding can be optimised but is probably quite fast due to the mesh creation has already done the work in the structuring. It is probably more important to try to analyse the current edge cases as there are only a few, it might be possible to put the two iterations into one.  At moment most effort is probably absorbed in my test in converting string path data into the required data structure and this is maybe sometimes done in macro when possible.

**Comment by Justinfront** [comment]
I have some worries I am not deleting structures but that is not an imediate concern, will have to look at hxGeomAlgo, but I think hxDaedalus can probably do this fairly optimally if only we spent more time on understanding it's inner workings.

**Comment by totologic** [comment]
mmh ?

If you want to extract triangles from an object, I coded it:

https://code.google.com/p/daedalus-lib/wiki/MeshDatasExtractionFromBitmap

But only for objects from bitmaps. Because it ensures me that the object is
safe.

Dealing with arbitraty objects is not a trivial task. You must first
clearly define what you want to retrieve. What is hole, what is not. Do we
want boolean operations or not  ?

Cedric

2015-05-27 19:49 GMT+02:00 Giuseppe Di Mauro <notifications@github.com>:

**Comment by Justinfront** [comment]
Cedric thinking harder my solution is nieve but partially correct.
Did you play with the letters example?
Firstly the letters are taken from flash and vectorized by a flash library so they are essentually from bitmaps and so are safe.  But we are only considering safe.  For instance you will notice the Path code has a dim() method that provides the min and max and centre so if you size the mesh significantly larger than you need and it will keep all curves within, essentially loops through to get extents and centre and make sure you place in a significantly bigger mesh but if it doubt we can resolve the curves with quadTo to get actual drawn lineTo's and the drawn assumed size.

So if we assume path finding as a solution ( maybe not optimal ? ) we can sort triangles into groups just by pathfinding within a group.
Now the group that is connected to the outside is the background and can be removed. 
Now the next group should be treated as a fill.
The one within as background and so on.
So it should be feasible to deal with all safe examples. 
We have access to all triangles so we can group them and we can work out which group is only connected to the outer edge and which group connected to that etc...
If you have not tried the code and played then you may not have an idea of how it can currently seem so close.  Really we need to find difficult safe examples.  But I suspect the current mesh and mesh.traverse does provide a good starting point.

**Comment by Justinfront** [comment]
My current assumption is that the current system can always resolve areas hence mesh.traverse can draw the borders because it passes edges which you can check  if ( edge.isConstrained ){
And from this experiment I found you can path find within an island.
https://rawgit.com/Justinfront/hxDaedalus-NME-OpenFL-Examples/master/hxDaedalus-NME-OpenFL-Examples/06-Multilayer/bin/html5/bin/index.html
So rather than pathfind we need groupfind! we can do that badly with pathfind.

**Comment by Justinfront** [comment]
so
1) draw a mesh bigger than the quadTo -> lineTo path dimensions (loop to find min max x and y )
1) for every triangle sort into groups.
2) check which group is connected to outside.
3) check which group is connected to each of these fill group but not the outside.
recurse.

**Comment by azrafe7** [comment]
Thanks for the quick answer!

So @Justinfront, @totologic... if I'm getting it right:

 - the wanted result is to extract a (constrained) Delaunay triangulation from plain float coords (as opposed to a BitmapData)
 - support for holes, which could be probably passed in with an opposite winding
 - all of this working only if the user deals with a safe/sanitized input

@totologic, am I correct in saying that `safe` means "with clear bounds and no duplicate vertices"?

If that's the case then I think it should be pretty simple to build this functionality on top of what you have already implemented (https://code.google.com/p/daedalus-lib/wiki/MeshDatasExtractionFromBitmap). With the minimal differences being: avoid building from the BitmapData, directly pass in an array of shapes (coords), and force the user to specify the boundaries (or maybe compute them at runtime as @Justinfront suggested). Something like:

```haxe
static public function extractMeshFromShapes(shapes:Array<Array<Float>>, width:Int, height:Int, vertices:Array<Point2D>, triangles:Array<Int>)
```

Now, to be fair, I've tried to test this solution with our haxe port of the lib, but I'm getting `indicesDict` pointing to null values. It's possible that there's still some bug in our port, but I'm not sure... does this approach seem sound to you? (in all sincerity it does to me, but... ;).

I'll see if I can test this more with the AS3 version to know if the issue is on our haxe side (though it won't be easy to come up with an example reproducing the issue). Any feedback would be greatly appreciated (and having the lib be capable of doing this would be really great!).

**Comment by azrafe7** [comment]
...And it works! \o/

It's basically @totologic's code (the one you, @Justinfront, already ported) with the simple rules described above applied.
Not sure what was doing wrong in my previous test, or changed in the current one. Anyway:

 - duplicate vertices are allowed (actually if I remove duplicate points I get more triangles back - can this be related to point order/position in the array?)
 - holes must be passed in CW winding
 - non-holes in CCW winding

(so to make it work for your example, @Justinfront, you'll need to reverse() all `coord` arrays)

I'm going to refactor it a bit (so both methods in Tools can share some code), and send a PR your way.

Kudos to @totologic for the help!

**Comment by Justinfront** [comment]
That sounds good I am keen to see the result.  Did you see how it 
compared to your other library approach in terms of speed, just curious 
really.

In Paris at moment I might make time to work on it but think tonight I 
am going to find some night life.

Best Justin

**Comment by azrafe7** [comment]
It's not really a proper benchmark, but I just tested both libs with your letters example, and Tess2 is approx 5 times faster (on average, varies between targets), but produces almost twice the number of tris (496 vs 258 of daedalus). They are also of _poor_ quality - many long and skinny ones -.

But the result is to be expected, since Tess2 doesn't output a Delaunay triangulation (which requires satisfying many more constraints).

Enjoy Paris and the WWX!

**Comment by Justinfront** [comment]
Wow it worked well I just took the liberty of adding a way to easily switch the winding ( extra ) optional parameter  ?CCW = true )  by setting it to false my letter example now works again :)
