### ISSUE TITLE
MultiLayer pathFinder

### ISSUE THREAD

**Issue by Richtervn** [hxDaedalus/hxDaedalus#72]
Hey guys, please help me out!
I did read the multilayer example and I can't get it as I don't know much about haxe.
I can read and understand it on pure js example.

All I need is just the logic to find path on multilayer. Can you please explain it ?
I'm trying to make a game like heroes 3 just for fun. How can I handle the portal that only one-direction ?

**Comment by Justinfront** [comment]
Hi Richtervn

Noticed your using React, you can find information on React with Haxe here:
https://github.com/massiveinteractive/haxe-react
and also places like.
https://github.com/elsassph/haxe-react-redux

So you can ditch coding in Javascript directly ;)

Having said that I am not convinced by React, but it's popular.

The multilayer example is not supported by hxDaedalus in pure js at moment, as it requires other libraries, the portals are created by mixing hxDaedalus for the images, with a more traditional pathfinding and using them as portals, so it's kind of a hybrid pathfinding approach, using the polygonal's ds.ai and ds package.

http://lab.polygonal.de/2011/07/22/a-pathfinding-with-ds/
http://lab.polygonal.de/2007/06/13/data-structures-example-the-graph-class/

You will notice that arc's are normally Uni-directional in the first diagram in second link ( use 't' to test traverse ).

If you look at the code, you can see that currently the setup is for Multi-directional.

https://github.com/hxDaedalus/hxDaedalus-NME-OpenFL-Examples/blob/master/hxDaedalus-NME-OpenFL-Examples/06-Multilayer/src/SubGraph.hx#L66

https://github.com/hxDaedalus/hxDaedalus-NME-OpenFL-Examples/blob/master/hxDaedalus-NME-OpenFL-Examples/06-Multilayer/src/SubGraph.hx#L51

You can see where it's used here:
https://github.com/hxDaedalus/hxDaedalus-NME-OpenFL-Examples/blob/master/hxDaedalus-NME-OpenFL-Examples/06-Multilayer/src/Main.hx#L116
and here
https://github.com/hxDaedalus/hxDaedalus-NME-OpenFL-Examples/blob/master/hxDaedalus-NME-OpenFL-Examples/06-Multilayer/src/Main.hx#L142

So you would need to modify SubGraph by adding new methods to access 'addSingleArc'
https://github.com/polygonal/ds/blob/master/src/de/polygonal/ds/Graph.hx#L202

But obviously the data defining the portals does not currently have a singleArc option as defined by the location and connections here.
https://github.com/hxDaedalus/hxDaedalus-NME-OpenFL-Examples/blob/master/hxDaedalus-NME-OpenFL-Examples/06-Multilayer/src/MultiLayerData.hx#L27
https://github.com/hxDaedalus/hxDaedalus-NME-OpenFL-Examples/blob/master/hxDaedalus-NME-OpenFL-Examples/06-Multilayer/src/MultiLayerData.hx#L56

So to get uni-directional flow would require some rethinking of the demo, but as outlined it is very feasible.

Really to do stuff like this you need to delve into Haxe properly I would not recomment the OpenFL toolkit as a starting point as your more familiar with javascript direct, I would suggest you just experiment with pure Haxe Javascript:

https://github.com/hxDaedalus/hxDaedalus-javascript-examples/tree/master/hxDaedalus-Examples
but you would need to move over the multilayer example, feel free to request a pull if you do this.

So it's a bit of work, sorry.  If you create a nice haxe react version of hxDaedalus and implement the hxDaedalus examples and document it and request it to be added as a new hxDaedalus folders then  I might look at adding a more flexible multilayer example for javascript, but my interest in supporting multilayer for pure js is pretty small as it's kind of out of the direct scope of hxDaedalus, and I want everyone to use haxe rather than js so I can find new job! :) So perhaps time to explore Haxe React, it's supposed to be a bit nicer than normal react?

Good Luck
 
Justin

**Comment by Richtervn** [comment]
Well, thanks for your nicely response !

As I can see, Haxe is really impressive and I should do a dive into it. But I did google a little about my whole country. Sadly, people here are not hiring Haxe developers and nobody tends to do this.

So, you said the multilayer won't be on pure js which means I'm doom. I can't see why this is out of the hxDaedalus' direct scope because you guys did give out an example about this. Please, make it in pure js example too. Be more reliable guys.

**Comment by Justinfront** [comment]
https://www.google.com/maps/d/viewer?mid=1YmTl7RSNp6Ytv_J7Ca6qJnsENCs&hl=en_US&ll=-24.91134916308581%2C53.3056640625&z=2

**Comment by Justinfront** [comment]
Richtervn

I have asked polygonal if he is willing to support precompiled versions of his libraries ds and ds.ai.
https://github.com/polygonal/ai/issues/2

This would be needed for us to consider adding this demo to javascript examples, this example is not fundimental for getting to grips with using hxDaedalus it's more of a bonus for advanced users to explore. 

But I think really you should explore haxe it may not be as hard as you imagine, and there are many places to learn like #haxe irc.

Best 

Justin

**Comment by Richtervn** [comment]
![http://i.imgur.com/QBGlP7k.png](http://i.imgur.com/QBGlP7k.png)

I modified MultilayerData to have something like this, and the pathfinding doesn't work anymore

**Comment by Justinfront** [comment]
top middle node looks like it is a fill did you move it?

**Comment by Justinfront** [comment]
I think really you should create lots of nodes close together for the bottom one rather than try to use the same node, it might be that looping code that sets up the nodes was not really designed or thought about to reuse a node.
