### ISSUE TITLE
Add field of view 

### ISSUE THREAD

**Issue by Ali-RS** [hxDaedalus/hxDaedalus#74]
Hi 
Will be cool to add field of view implementation on hxDaedalus
here is the action script implementation from @totologic

https://github.com/ColinGilbert/daedalus-lib/commit/e63903467cb76ebcee9ac3b0435be901d37628b4

Thanks

**Comment by nanjizal** [comment]
Ali-RS
Do you need this feature for a current application what target are you using? 
I have some reservations - Ideally to get code to work in Kha etc... I would like to reduce graphics coupling, moving all render aspects from the core so reluctant to add logic on the render side. For instance for use for 2D in away3d-core-openfl a radius render control would be wasted since away3d provides control over the render window.  My understanding after browsing the link is this relates purely to the radius of render and not to the pathfinding aspects?  Or is this feature related to pathfinding / triangulation code?  It should not be too hard to add mostly just changing some names, do you have a simple demo as3 example use?
Best
Nanjizal

**Comment by Ali-RS** [comment]
Thanks for quick response @nanjizal 

> Do you need this feature for a current application what target are you using?
Brief explanation of my project. 
I am working on a MMORPG game developed with jMonkeyEngine (Java game engine). 
I am using the java version of your project see https://github.com/implicit-invocation/jwalkable.
All the AI and Physic stuffs done in server side and completely decoupled from ui and graphics. 

> My understanding after browsing the link is this relates purely to the radius of render and not to the pathfinding aspects? Or is this feature related to pathfinding / triangulation code? 

Too be honest I have not taken a deep look at the code and do not know how it works internally. 
After shallow look yes it seems his code is coupled with flash graphic api  which in this case it will not be of any help for my  case.

Sorry for my misunderstanding! 
And thanks a lot for your time.
