### ISSUE TITLE
null in listEdges

### ISSUE THREAD

**Issue by fnaith** [hxDaedalus/hxDaedalus#76]
I recently use hxDaedalus in my game for pathfinding ai, which save my day and work fine, usually.

The problem is sometimes when I call PathFinder.findPath, Geom2D.getRelativePosition2 throws NullPointerException because currEdge is null. The exception looks like:

![stacktrace](https://user-images.githubusercontent.com/11421034/45274388-de043f00-b4e9-11e8-984f-99d289602a74.PNG)

IMHO, it seems happened when main character is moving along edge. But I cannot identify the real root cause.

I also clone [Example Project](https://github.com/hxDaedalus/hxDaedalus-Examples/tree/master/hxDaedalus-Examples/web) and try to simulate this situation by hard code coordinate and target mouse position. but sadly the different error shown when I click mouse (maybe it uses different hxDaedalus version?) .
![error-log](https://user-images.githubusercontent.com/11421034/45274622-de510a00-b4ea-11e8-95f8-26661a28f09d.PNG)

[daedalusPathfinding.js.txt](https://github.com/hxDaedalus/hxDaedalus/files/2365020/daedalusPathfinding.js.txt)

Could you guys help ? (´;ω;`)

**Comment by azrafe7** [comment]
Hello @fnaith, I've investigated this a bit but haven't found a fix for it (long time since I've played with the lib).

From what I gather the problem seems to be exactly what you suggest: moving from/along some _particular_ edges may cause the algo to not find in what face (triangle) the entity is - most probably due to some small numerical errors -, so no reference edge is found.

@Justinfront do you have any more insights on what is exactly happening here and maybe how to fix it?

On an unrelated note, you can insert the walkable areas into the mesh instead of the unwalkable ones, or use a bitmap to handle that for you and get this:

![image](https://user-images.githubusercontent.com/1266447/45309633-63a4e080-b524-11e8-864d-8ee0c2521e3e.png)

**Comment by azrafe7** [comment]
@fnaith, you can try changing this line: https://github.com/hxDaedalus/hxDaedalus/blob/ae7eeaff9b5359c2a4ee6c8e54eea30845fbd475/src/hxDaedalus/ai/Funnel.hx#L204 
to 
```haxe
  if (listEdges.length > 1) listEdges.shift();
```

A bit _hacky_ for my tastes, but let me know if it works for you.

**Comment by azrafe7** [comment]
Naah, forget it. Still wrong.

**Comment by fnaith** [comment]
lol

**Comment by azrafe7** [comment]
For now I can only add that I've tried using the original AS3 version of the daedalus lib by totologic, and the issue is reproducible there too.

(https://gist.github.com/azrafe7/63e7a9b18747613698598003de4f1791)

**Comment by fnaith** [comment]
I believe Haxe version shares same structure as AS3 version.

Wishing totologic will response this issue.

BTW thanks for gist, I don't familiar with AS3 so that couldn't report detail message to totologic . :P

**Comment by azrafe7** [comment]
Maybe I've found a way to solve this, or at least found what's the cause of it.

My understanding so far is that the problem only arises when the entity is lying _exactly_ on a shared edge between two faces, and the algo is asked to go into _exactly_ one of them. But since it removes the first edge and face in the path (which works correctly when traversing more than one face), it then has no way to go further.

Try pasting this:

```haxe
        if (listFaces.length == 1) // (issue76)
        {
            resultPath.push(startPoint.x);
            resultPath.push(startPoint.y);
            resultPath.push(endPoint.x);
            resultPath.push(endPoint.y);
            return;
        }
```

just after this switch

https://github.com/hxDaedalus/hxDaedalus/blob/ae7eeaff9b5359c2a4ee6c8e54eea30845fbd475/src/hxDaedalus/ai/Funnel.hx#L199-L209

**Comment by fnaith** [comment]
So first I paste code as following:
```Haxe
class Funnel
{
    public var radius(get, set) : Float;

    static public var flag:Bool = false; // for switch (issue76) patch
...
	//TODO: check if this needs ENull (/not EEdge) checks
        switch( Geom2D.isInFace(fromX, fromY, listFaces[0]) )
        {
            case EEdge( edge ):
                if( listEdges[0] == edge )
                {
                    listEdges.shift();
                    listFaces.shift();
                }
            case _:
        }
        if (flag && listFaces.length == 1) // (issue76)
        {
            resultPath.push(startPoint.x);
            resultPath.push(startPoint.y);
            resultPath.push(endPoint.x);
            resultPath.push(endPoint.y);
            return;
        }
        // our funnels, inited with starting point
```

then update origin enemy ai like:
```Haxe
//if (allowPath)
{
    Funnel.flag = false;
    pathFinder.entity.radius = ds._circleShape.get(entity).getRadius();
    pathFinder.entity.x = entityPosition.getX() + PathService.OFFSET;
    pathFinder.entity.y = entityPosition.getY() + PathService.OFFSET;
    try // TODO wait for https://github.com/hxDaedalus/hxDaedalus/issues/76
    {
        pathFinder.findPath(playerPosition.getX() + PathService.OFFSET, playerPosition.getY() + PathService.OFFSET, path);
        if (0 != path.length)
        {
            lastPlayerX = playerPosition.getX();
            lastPlayerY = playerPosition.getY();
        }
        else
        {
            pathFinder.findPath(lastPlayerX + PathService.OFFSET, lastPlayerY + PathService.OFFSET, path);
        }
        pathSampler.reset();
    }
    catch (unknown:Any)
    {
        nekosith.log.Log.error("pathFinder.findPath error");
        Funnel.flag = false;
        try
        {
            pathFinder.findPath(playerPosition.getX() + PathService.OFFSET, playerPosition.getY() + PathService.OFFSET, path);
            nekosith.log.Log.error("pathFinder.findPath re-try ok");
        }
        catch (unknown:Any)
        {
            nekosith.log.Log.error("pathFinder.findPath re-try still fail");
        }
        //pathFinder = ds._PathService.generatePathFinder(entityAI);
    }
}
```

And it looks fine!
![looks-ok](https://user-images.githubusercontent.com/11421034/45591825-f6fc6c80-b98f-11e8-857e-11e480cede31.PNG)

@azrafe7  looks like you save the day!

**Comment by azrafe7** [comment]
Glad it worked.

**Comment by fnaith** [comment]
Thanks so much. ( ^ω^)

**Comment by azrafe7** [comment]
Hey @Justinfront, happy to hear back from you.
Anyway no worries, glad to know you were following the process.

The pushes-block cannot be moved inside the switch as is...
The issue here - as I understood it - was that when we're lying on an edge shared by two faces and moving into one of them, the astar algo reported 2 faces and 1 edge (the shared one). But then removed 1 face AND 1 edge (inside the switch), resulting in the list of edges-to-traverse to be empty. Thus crashing.
Now both cases (move from-and-to inside the same face, and move from a shared edge to somewhere inside the other face) are handled by the second `if`, letting the first `if` (the one with the switch) do its job, if needed.

As for the flash bug regarding push() I'm not up to date about it. But if it's a serious one we will have to make changes in many places since we used plenty of push()es throughout the codebase.

(@fnaith maybe you intended to mention me instead of Anders, right?! :P)

**Comment by fnaith** [comment]
Maybe~~~ :P
